#!/bin/sh
case "$1" in
    start)
        cd /maixapp/apps/menu_selector
        python3 main.py &
        ;;
    stop)
        killall -9 python3
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
exit 0
